name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish binary for version ${{ github.ref }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [linux]

        include:
          - name: linux
            os: ubuntu-latest
            artifact_name: target/release/dmr-bridge-discord
            asset_name: dmr-bridge-discord-linux

    steps:
    - uses: actions/checkout@v3

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        
    - uses: Swatinem/rust-cache@v2

    - name: Build
      run: cargo build --release
      
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ matrix.asset_name }}
        files: ${{ matrix.artifact_name }}

